// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6a2-x_EmrLF-7LCCw_s0CVW0l3OtH59Q',
    appId: '1:552083831861:web:477c2f3cf2ec27b37fc57c',
    messagingSenderId: '552083831861',
    projectId: 'flutter-chat-app-7d945',
    authDomain: 'flutter-chat-app-7d945.firebaseapp.com',
    storageBucket: 'flutter-chat-app-7d945.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD78sUFxAMN-05fDzCBCsk6c3Izq-FvYho',
    appId: '1:552083831861:android:b279470654ffb28d7fc57c',
    messagingSenderId: '552083831861',
    projectId: 'flutter-chat-app-7d945',
    storageBucket: 'flutter-chat-app-7d945.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA17AlDeKh-PYrYpTgSwYZ7gzFaTRPFxDk',
    appId: '1:552083831861:ios:148759f0c39182f27fc57c',
    messagingSenderId: '552083831861',
    projectId: 'flutter-chat-app-7d945',
    storageBucket: 'flutter-chat-app-7d945.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA17AlDeKh-PYrYpTgSwYZ7gzFaTRPFxDk',
    appId: '1:552083831861:ios:148759f0c39182f27fc57c',
    messagingSenderId: '552083831861',
    projectId: 'flutter-chat-app-7d945',
    storageBucket: 'flutter-chat-app-7d945.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6a2-x_EmrLF-7LCCw_s0CVW0l3OtH59Q',
    appId: '1:552083831861:web:af5803849b002c097fc57c',
    messagingSenderId: '552083831861',
    projectId: 'flutter-chat-app-7d945',
    authDomain: 'flutter-chat-app-7d945.firebaseapp.com',
    storageBucket: 'flutter-chat-app-7d945.appspot.com',
  );

}